### ISSUE TITLE
Files that are to be ignored are committed

### ISSUE THREAD

**Issue by krerkkiat** [alexshelto/Lets-Play-webapp#6]
@alexshelto The `__pycache__` folder should be ignored. Please look into what files should be ignored for Python.  You can assign Hunter Burden if you want. I don't see any commit from this student.

**Comment by krerkkiat** [comment]
The steps are to remove all `__pycache__` folders from the repository, and then add appropriate line to the `.gitignore` file.

**Comment by alexshelto** [comment]
.gitignore has been fixed, if someone wants to make a pull req for the '__pycache__' dirs
